# @package _global_

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

  # output_subdir: null

  job_logging:
    root:
      handlers: [console, file]
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    logging:
      version: 1
      disable_existing_loggers: false
      handlers:
        console:
          class: logging.StreamHandler
          stream: ext://sys.stdout
          formatter: simple
          level: INFO
        # file:
        #   class: logging.FileHandler
        #   filename: 'dummy'  # この値はPythonコード内で動的に置き換えられます
        #   formatter: simple
        #   level: INFO
      root:
        level: INFO
        handlers: [console, file]
